name: Lint

on: [push]

jobs:
 lint:
  name: ESLint
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    node: ["lts/*"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v5
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node }}
      cache: "npm"
   - name: 🚀 Install dependencies
     run: npm install
   - name: 🚀 Run ESLint
     run: npm run lint
